### ISSUE TITLE
[Student feedback] Add ref to tilt-dok

### ISSUE THREAD

**Issue by eliasgruenewald** [DaSKITA/tilter#106]
<img width="1066" alt="Screenshot 2021-06-22 at 13 14 23" src="https://user-images.githubusercontent.com/18154624/122915178-c5443b80-d35b-11eb-9d82-89d24015d9b2.png">

We could add a simple link to the tilt doc in the task overview (e.g. little chain icon which links to api/task/\<id\>/tilt).

**Comment by fmaschhur** [comment]
This is solved in the branch /features/link-to-tilt-doc by adding a reference link to the labeling view of a task (
![screenshot](https://user-images.githubusercontent.com/16879076/128871491-22f9f537-64cb-485c-bb22-6eddc824fea8.png)). How important is the addition of such links to the task overview?

**Comment by eliasgruenewald** [comment]
it's perfect like this - no need to change the task overview!
